lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]    

superlists/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from lists import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'superlists.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.home_page, name='home'),
    url(r'^lists/new$', 'lists.views.new_list', name='new_list'),
    url(r'^lists/(\d+)/$', 'lists.views.view_list', name='view_list'),
    url(r'^lists/(\d+)/add_item$', views.add_item, name='add_item'),
    # url(r'^admin/', include(admin.site.urls)),
)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

class List(models.Model):
	def get_absolute_url(self):
		return reverse('view_list', args=[self.id])

class Item(models.Model):
	text = models.TextField(default='', unique=True)
	list = models.ForeignKey(List, default=None)

lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render
from lists.models import Item, List

def home_page(request):
	komentar = "Yey, waktunya berlibur"
	return render(request, 'home.html', {'komentar': komentar})

def view_list(request, list_id):
	list_ = List.objects.get(id=list_id)
	count_list = Item.objects.filter(list_id=list_id).count()
	error = None
	komentar = ""

	if count_list == 0:
		komentar = "Yey, waktunya berlibur"
	elif count_list < 5:
		komentar = "Sibuk tapi santai"
	else:
		komentar = "Oh tidak"

	if request.method == 'POST':
		try:
			item = Item(text=request.POST['item_text'], list=list_)
			item.full_clean()
			item.save()
			return redirect(list_)
		except ValidationError:
			error = "You can't have an empty list item"

	return render(request, 'list.html', {'komentar': komentar, 'list': list_, 'error': error})

def new_list(request):
	list_ = List.objects.create()
	item = Item(text=request.POST['item_text'], list=list_)
	try:
		item.full_clean()
		item.save()
	except ValidationError:
		list_.delete()
		error = "You can't have an empty list item"
		return render(request, 'home.html', {"error": error})
	return redirect(list_)	

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Novie Kamalia - 1206239806</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/base.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">

			<div class="row">
				<div class="col-md-6 col-md-offset-3 jumbotron">
					<div class="text-center">
						<h1>{% block header_text %}{% endblock %}</h1>
						<form method="POST" action="{% block form_action %}{% endblock %}">
							<input name="item_text" id="id_new_item" class="form-control input-lg" placeholder="Enter a to-do item"/>
							{% csrf_token %}

							{% if error %}
								<div class="form-group has-error">
									<span class="help-block">{{ error }}</span>
								</div>
							{% endif %}
						</form>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="alert alert-info">
						<h4> {{ komentar }} </h4>
					</div>
					{% block table %}
					{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html>

lists/templates/home.html
<html>
	<head>
		<title>Novie Kamalia - 1206239806</title>
	</head>
	<body>
		{% extends 'base.html' %}
		{% block header_text %}Start a new To-Do list{% endblock %}
		{% block form_action %}{% url 'new_list' %}{% endblock %}
		<h4> {{ komentar }} </h4>
	</body>
</html>

lists/templates/list.html
<html>
	<head>
		<title>Novie Kamalia - 1206239806</title>
	</head>
	<body>
		{% extends 'base.html' %}

		{% block header_text %}Your To-Do list{% endblock %}

		{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

		<h4> {{ komentar }} </h4>

		{% block table %}
			<table id="id_list_table" class="table">
				{% for item in list.item_set.all %}
					<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
				{% endfor %}
			</table>
		{% endblock %}
	</body>
</html>